In [1]:
%pip install h5py numpy rasterio

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ------------------ --------------------- 1.3/2.9 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 7.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.8 MB 9.6 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.8 MB 8.8 MB/s eta 0:00:02
   ------------- -------------------------- 4.5/12.8 MB 7.7 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.8 MB 7.9 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/12.8 MB 7.5 MB/s eta 0:00:01
   --------------------------- ------------ 8.9/12.8 MB 7.3 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.8 MB 7.1 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.8 MB 6.7 MB/s eta 0:00:01
   ----------


[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
%pwd

'c:\\Users\\tarozzokawasakiml\\git\\DigitalEarth\\DigitalEarth'

In [23]:
import h5py
import os

folder_path = 'data/data/2021/01'  # Remove 'DigitalEarth/' since you're already in that folder

# List all .h5 files in the folder
h5_files = [f for f in os.listdir(folder_path) if f.endswith('.h5')]

for filename in h5_files:
    file_path = os.path.join(folder_path, filename)
    with h5py.File(file_path, 'r') as f:
        print(f"Opened: {filename}")
        f.visit(lambda name: print(f"  {name}"))


Opened: RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5
  geographic
  geographic/map_projection
  image1
  image1/calibration
  image1/image_data
  overview
  radar1
  radar2
  radar3
Opened: RAD_NL25_RAC_MFBS_EM_5min_202101010005_NL.h5
  geographic
  geographic/map_projection
  image1
  image1/calibration
  image1/image_data
  overview
  radar1
  radar2
  radar3
Opened: RAD_NL25_RAC_MFBS_EM_5min_202101010010_NL.h5
  geographic
  geographic/map_projection
  image1
  image1/calibration
  image1/image_data
  overview
  radar1
  radar2
  radar3
Opened: RAD_NL25_RAC_MFBS_EM_5min_202101010015_NL.h5
  geographic
  geographic/map_projection
  image1
  image1/calibration
  image1/image_data
  overview
  radar1
  radar2
  radar3
Opened: RAD_NL25_RAC_MFBS_EM_5min_202101010020_NL.h5
  geographic
  geographic/map_projection
  image1
  image1/calibration
  image1/image_data
  overview
  radar1
  radar2
  radar3
Opened: RAD_NL25_RAC_MFBS_EM_5min_202101010025_NL.h5
  geographic
  geographic/map_project

STEP 1: Read h5 files and understand which attributes are in it.

In [24]:
import h5py
file_path = 'data/data/2021/01/RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5'

with h5py.File(file_path, 'r') as f:
    dataset = f['image1/image_data']
    print("Shape:", dataset.shape)
    print("Attributes:")
    for key, value in dataset.attrs.items():
        print(f"  {key}: {value}")

Shape: (765, 700)
Attributes:
  CLASS: [b'IMAGE']
  VERSION: [b'1.2']


In [31]:
import h5py
file_path = 'data/data/2021/01/RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5'

with h5py.File(file_path, 'r') as f:
    dataset = f['image1/calibration']
    print("Attributes:")
    for key, value in dataset.attrs.items():
        print(f"  {key}: {value}")

Attributes:
  calibration_flag: b'Y'
  calibration_formulas: [b'GEO = 0.010000 * PV + 0.000000']
  calibration_missing_data: [65535]
  calibration_out_of_image: [65535]


In [32]:
import h5py
file_path = 'data/data/2021/01/RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5'

with h5py.File(file_path, 'r') as f:
    dataset = f['image1']
    print("Attributes:")
    for key, value in dataset.attrs.items():
        print(f"  {key}: {value}")

Attributes:
  image_bytes_per_pixel: [2]
  image_geo_parameter: b'ACCUMULATED_PRECIPITATION_[MM]'
  image_product_name: [b'RAD_NL25_RAC_MFBS_5min']
  image_size: [1071000]


In [35]:
import h5py
file_path = 'data/data/2021/01/RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5'

with h5py.File(file_path, 'r') as f:
    rainfall_mm_5min = f['image1/image_data'][:]
    rainfall_mm_per_hour = rainfall_mm_5min * 12  # Convert to mm/hour
    print(rainfall_mm_per_hour[:5, :5])  # Show a sample

[[65524 65524 65524 65524 65524]
 [65524 65524 65524 65524 65524]
 [65524 65524 65524 65524 65524]
 [65524 65524 65524 65524 65524]
 [65524 65524 65524 65524 65524]]


In [36]:
import h5py
file_path = 'data/data/2021/01/RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5'

with h5py.File(file_path, 'r') as f:
    dataset = f['image1/image_data']
    print("Attributes:")
    for key, value in dataset.attrs.items():
        print(f"  {key}: {value}")

Attributes:
  CLASS: [b'IMAGE']
  VERSION: [b'1.2']


In [37]:
import h5py
import numpy as np

file_path = 'data/data/2021/01/RAD_NL25_RAC_MFBS_EM_5min_202101010000_NL.h5'

with h5py.File(file_path, 'r') as f:
    rainfall_mm_5min = f['image1/image_data'][:]
    rainfall_mm_5min = np.where(rainfall_mm_5min == 65524, np.nan, rainfall_mm_5min)
    rainfall_mm_per_hour = rainfall_mm_5min * 12
    print(rainfall_mm_per_hour[:5, :5])  # Show a sample

[[786420. 786420. 786420. 786420. 786420.]
 [786420. 786420. 786420. 786420. 786420.]
 [786420. 786420. 786420. 786420. 786420.]
 [786420. 786420. 786420. 786420. 786420.]
 [786420. 786420. 786420. 786420. 786420.]]
